apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: policy-infra-adhp-dev-tls
spec:
  dnsNames:
  - policy.infra.adhp.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: policy-infra-adhp-dev-tls