apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vatsim-gcp-store
spec:
  provider:
      gcpsm:                                  # gcpsm provider
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: vatsim-gcpsm-secret
              key: secret-access-credentials
              namespace: external-secrets
        projectID: vatsim-adh
