apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bulldozer-infra-alphawhiskey-org-tls
  namespace: bulldozer-bot
spec:
  dnsNames:
  - bulldozer.infra.alphawhiskey.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: bulldozer-infra-alphawhiskey-org-tls