apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bulldozer-bot
  namespace: bulldozer-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: bulldozer-bot
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: bulldozer-bot