apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bulldozer-bot-ingress
  namespace: bulldozer-bot
  labels:
    app: bulldozer-bot
spec:
  ingressClassName: nginx
  rules:
  - host: bulldozer.infra.alphawhiskey.org
    http:
      paths:
      - backend:
          service:
            name: bulldozer-bot
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - bulldozer.infra.alphawhiskey.org
    secretName: bulldozer-infra-alphawhiskey-org-tls